[target.xtensa-esp32-espidf]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = ".github/configs/sdkconfig.defaults"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

# Configure the espidf_time64 Rust compiler flag to build with ESP-IDF 5.*.
# Must be disabled to build with ESP-IDF 4.*.
# [build]
# rustflags = "--cfg espidf_time64"
